name: ESLint

on: pull_request

jobs:
  eslint:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run ESLint
        run: yarn eslint ./src --ext .js,.jsx,.ts,.tsx
