name: TypeScript type check

on: pull_request

jobs:
  tsc:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Yarn & setup
        run: yarn install
      - name: (temporary) Remove scripts/ files except for types.ts
        run: |
          cp ./scripts/types.ts .
          rm -rf ./scripts
          mkdir scripts
          mv ./types.ts scripts
      - name: Typecheck
        run: |
          yarn tsc -v
          yarn tsc -p ./tsconfig.json
